<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ExportProductSeeder extends Seeder
{
    public function run(): void
    {
        $exports = [
            [
                'village_id' => 32010101,
                'product_id' => 1,
                'created_by' => 1,
                'name' => 'Beras Organik Premium Grade A',
                'slug' => 'beras-organik-premium-grade-a',
                'description' => 'Beras organik premium kualitas ekspor dari Desa Nanggung. Ditanam tanpa pestisida kimia, proses panen manual, dan penggilingan modern. Telah memenuhi standar internasional.',
                'image' => 'https://picsum.photos/seed/export1/1200/800',
                'gallery' => json_encode(['https://picsum.photos/seed/export1a/800/600', 'https://picsum.photos/seed/export1b/800/600']),
                'hs_code' => '1006.30',
                'destination_countries' => json_encode(['Jepang', 'Singapura', 'Malaysia']),
                'export_status' => 'sudah_ekspor',
                'certifications' => json_encode(['Organik Nasional', 'JAS Organic', 'HALAL MUI']),
                'has_export_license' => true,
                'export_volume' => 5000,
                'export_value' => 35000.00,
                'unit' => 'kg',
                'contact_person' => 'Pak Hasan',
                'contact_phone' => '081234567001',
                'contact_email' => 'export.nanggung@gmail.com',
                'is_active' => true,
                'is_featured' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'village_id' => 32010301,
                'product_id' => 3,
                'created_by' => 1,
                'name' => 'Furniture Bambu Handmade',
                'slug' => 'furniture-bambu-handmade',
                'description' => 'Furniture bambu berkualitas tinggi buatan tangan pengrajin Desa Ciampea. Desain modern minimalis dengan material bambu pilihan yang telah melalui proses treatment anti rayap.',
                'image' => 'https://picsum.photos/seed/export2/1200/800',
                'gallery' => json_encode(['https://picsum.photos/seed/export2a/800/600', 'https://picsum.photos/seed/export2b/800/600']),
                'hs_code' => '9401.69',
                'destination_countries' => json_encode(['Australia', 'Jerman', 'Belanda']),
                'export_status' => 'sudah_ekspor',
                'certifications' => json_encode(['FSC Certified', 'SNI']),
                'has_export_license' => true,
                'export_volume' => 200,
                'export_value' => 28000.00,
                'unit' => 'pcs',
                'contact_person' => 'Bu Ratna',
                'contact_phone' => '081234567002',
                'contact_email' => 'bambu.ciampea@gmail.com',
                'is_active' => true,
                'is_featured' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'village_id' => 32040101,
                'product_id' => null,
                'created_by' => 1,
                'name' => 'Kopi Arabika Specialty Ciwidey',
                'slug' => 'kopi-arabika-specialty-ciwidey',
                'description' => 'Kopi arabika specialty grade dari perkebunan dataran tinggi Ciwidey (1.200 mdpl). Single origin, proses natural dan honey, cupping score 84+.',
                'image' => 'https://picsum.photos/seed/export3/1200/800',
                'gallery' => json_encode(['https://picsum.photos/seed/export3a/800/600']),
                'hs_code' => '0901.21',
                'destination_countries' => json_encode(['Korea Selatan', 'Jepang', 'Taiwan']),
                'export_status' => 'proses_ekspor',
                'certifications' => json_encode(['UTZ Certified', 'Rainforest Alliance', 'HALAL']),
                'has_export_license' => true,
                'export_volume' => 1500,
                'export_value' => 18500.00,
                'unit' => 'kg',
                'contact_person' => 'Pak Dedi',
                'contact_phone' => '081234567003',
                'contact_email' => 'kopi.ciwidey@gmail.com',
                'is_active' => true,
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'village_id' => 51080301,
                'product_id' => null,
                'created_by' => 1,
                'name' => 'Kerajinan Perak Ubud',
                'slug' => 'kerajinan-perak-ubud',
                'description' => 'Kerajinan perak sterling 925 buatan tangan pengrajin Ubud. Desain khas Bali dengan motif tradisional dan kontemporer. Setiap piece unik dan memiliki sertifikat keaslian.',
                'image' => 'https://picsum.photos/seed/export4/1200/800',
                'gallery' => json_encode(['https://picsum.photos/seed/export4a/800/600', 'https://picsum.photos/seed/export4b/800/600']),
                'hs_code' => '7113.11',
                'destination_countries' => json_encode(['Amerika Serikat', 'Inggris', 'Perancis', 'Australia']),
                'export_status' => 'sudah_ekspor',
                'certifications' => json_encode(['Sterling Silver 925', 'Handmade Certified']),
                'has_export_license' => true,
                'export_volume' => 500,
                'export_value' => 42000.00,
                'unit' => 'pcs',
                'contact_person' => 'Wayan Surya',
                'contact_phone' => '081234567004',
                'contact_email' => 'silver.ubud@gmail.com',
                'is_active' => true,
                'is_featured' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'village_id' => 51080201,
                'product_id' => null,
                'created_by' => 1,
                'name' => 'Minyak Kelapa VCO Premium',
                'slug' => 'minyak-kelapa-vco-premium',
                'description' => 'Virgin Coconut Oil (VCO) premium dari kelapa segar pilihan Bali. Proses cold-pressed tanpa pemanasan untuk mempertahankan nutrisi alami. Cocok untuk kesehatan dan kecantikan.',
                'image' => 'https://picsum.photos/seed/export5/1200/800',
                'gallery' => json_encode(['https://picsum.photos/seed/export5a/800/600']),
                'hs_code' => '1513.11',
                'destination_countries' => json_encode(['Singapura', 'Hong Kong', 'China']),
                'export_status' => 'proses_ekspor',
                'certifications' => json_encode(['BPOM', 'HALAL MUI', 'Organic']),
                'has_export_license' => false,
                'export_volume' => 2000,
                'export_value' => 12000.00,
                'unit' => 'liter',
                'contact_person' => 'Made Astini',
                'contact_phone' => '081234567005',
                'contact_email' => 'vco.mengwi@gmail.com',
                'is_active' => true,
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'village_id' => 32010102,
                'product_id' => null,
                'created_by' => 1,
                'name' => 'Teh Herbal Gunung Halimun',
                'slug' => 'teh-herbal-gunung-halimun',
                'description' => 'Teh herbal premium dari lereng Gunung Halimun. Campuran daun teh, jahe merah, sereh, dan rempah pilihan. Proses pengeringan alami untuk menjaga aroma dan khasiat.',
                'image' => 'https://picsum.photos/seed/export6/1200/800',
                'gallery' => json_encode([]),
                'hs_code' => '0902.10',
                'destination_countries' => json_encode(['Malaysia', 'Brunei']),
                'export_status' => 'potensial',
                'certifications' => json_encode(['BPOM', 'HALAL MUI']),
                'has_export_license' => false,
                'export_volume' => 800,
                'export_value' => 5500.00,
                'unit' => 'kg',
                'contact_person' => 'Pak Asep',
                'contact_phone' => '081234567006',
                'contact_email' => 'teh.halimun@gmail.com',
                'is_active' => true,
                'is_featured' => false,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('export_products')->insert($exports);
    }
}
