<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VillagePotentialSeeder extends Seeder
{
    public function run(): void
    {
        $potentials = [
            // Desa Nanggung — Pertanian
            [
                'village_id' => 32010101,
                'created_by' => 1,
                'category' => 'pertanian',
                'name' => 'Lahan Sawah Organik Nanggung',
                'description' => 'Lahan pertanian sawah organik seluas 150 hektar yang menghasilkan beras merah dan beras putih premium. Sistem irigasi teknis dari sungai Cidurian.',
                'image' => 'https://picsum.photos/seed/potensi1/1200/800',
                'total_area' => 150.00,
                'production_volume' => 900,
                'economic_value' => 4500000000,
                'is_investment_ready' => true,
                'investment_needs' => 'Mesin penggilingan modern, gudang penyimpanan berstandar, dan alat pertanian presisi untuk meningkatkan kapasitas produksi.',
                'development_status' => 'produktif',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Desa Malasari — Kehutanan
            [
                'village_id' => 32010102,
                'created_by' => 1,
                'category' => 'kehutanan',
                'name' => 'Hutan Bambu & Kayu Desa Malasari',
                'description' => 'Kawasan hutan desa dengan potensi bambu petung dan kayu albasia. Dikelola melalui LMDH (Lembaga Masyarakat Desa Hutan) untuk perhutanan sosial.',
                'image' => 'https://picsum.photos/seed/potensi2/1200/800',
                'total_area' => 320.00,
                'production_volume' => 250,
                'economic_value' => 2800000000,
                'is_investment_ready' => false,
                'investment_needs' => 'Teknologi pengolahan bambu, pembangunan workshop, dan sertifikasi kayu berkelanjutan (FSC).',
                'development_status' => 'dikembangkan',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Desa Ciampea — Industri
            [
                'village_id' => 32010301,
                'created_by' => 1,
                'category' => 'industri',
                'name' => 'Sentra Kerajinan Bambu Ciampea',
                'description' => 'Pusat industri kecil kerajinan bambu dengan 45 unit usaha aktif. Menghasilkan furniture, dekorasi, dan peralatan rumah tangga dari bambu.',
                'image' => 'https://picsum.photos/seed/potensi3/1200/800',
                'total_area' => 8.50,
                'production_volume' => 12000,
                'economic_value' => 6500000000,
                'is_investment_ready' => true,
                'investment_needs' => 'Mesin pengolahan bambu otomatis, showroom pameran, dan akses pasar digital untuk ekspor.',
                'development_status' => 'produktif',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Desa Alamendah — Perkebunan
            [
                'village_id' => 32040101,
                'created_by' => 1,
                'category' => 'perkebunan',
                'name' => 'Kebun Teh & Kopi Dataran Tinggi',
                'description' => 'Perkebunan teh dan kopi arabika di ketinggian 1.200 mdpl. Menghasilkan teh hitam premium dan kopi specialty grade dengan cupping score 84+.',
                'image' => 'https://picsum.photos/seed/potensi4/1200/800',
                'total_area' => 280.00,
                'production_volume' => 180,
                'economic_value' => 8500000000,
                'is_investment_ready' => true,
                'investment_needs' => 'Mesin roasting modern, fasilitas cupping lab, dan sertifikasi organic internasional.',
                'development_status' => 'produktif',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Desa Alam Endah — Peternakan
            [
                'village_id' => 32040201,
                'created_by' => 1,
                'category' => 'peternakan',
                'name' => 'Peternakan Domba Garut',
                'description' => 'Kawasan peternakan domba garut dengan populasi 2.000 ekor. Dikenal dengan kualitas daging dan wool premium. Program pembibitan unggul.',
                'image' => 'https://picsum.photos/seed/potensi5/1200/800',
                'total_area' => 45.00,
                'production_volume' => 600,
                'economic_value' => 3200000000,
                'is_investment_ready' => false,
                'investment_needs' => 'Kandang modern, fasilitas kesehatan hewan, dan cold storage untuk distribusi.',
                'development_status' => 'dikembangkan',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Desa Kuta — Pariwisata
            [
                'village_id' => 51080101,
                'created_by' => 1,
                'category' => 'pariwisata',
                'name' => 'Potensi Wisata Pantai & Budaya Kuta',
                'description' => 'Potensi wisata pantai kelas dunia dengan infrastruktur pendukung. Destinasi surfing internasional, sunset spot, dan pusat shopping. Dikunjungi 3 juta wisatawan/tahun.',
                'image' => 'https://picsum.photos/seed/potensi6/1200/800',
                'total_area' => 15.00,
                'production_volume' => 3000000,
                'economic_value' => 150000000000,
                'is_investment_ready' => true,
                'investment_needs' => 'Revitalisasi fasilitas publik, penataan pedagang kaki lima, dan pengembangan eco-tourism.',
                'development_status' => 'produktif',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Desa Mengwi — Perikanan
            [
                'village_id' => 51080201,
                'created_by' => 1,
                'category' => 'perikanan',
                'name' => 'Tambak Udang Vaname Mengwi',
                'description' => 'Kawasan budidaya udang vaname intensif dengan teknologi biofloc. 25 kolam produksi dengan total luas 12 hektar. Menghasilkan udang kualitas ekspor.',
                'image' => 'https://picsum.photos/seed/potensi7/1200/800',
                'total_area' => 12.00,
                'production_volume' => 360,
                'economic_value' => 18000000000,
                'is_investment_ready' => true,
                'investment_needs' => 'Sistem monitoring IoT, cold chain facility, dan sertifikasi Best Aquaculture Practices (BAP).',
                'development_status' => 'produktif',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Desa Ubud — SDM
            [
                'village_id' => 51080301,
                'created_by' => 1,
                'category' => 'sdm',
                'name' => 'Komunitas Seniman & Pengrajin Ubud',
                'description' => 'Komunitas 200+ seniman dan pengrajin lokal meliputi pelukis, pemahat, pembatik, dan perajin perak. Warisan budaya yang menjadi daya tarik wisata.',
                'image' => 'https://picsum.photos/seed/potensi8/1200/800',
                'total_area' => 5.00,
                'production_volume' => 50000,
                'economic_value' => 25000000000,
                'is_investment_ready' => true,
                'investment_needs' => 'Art gallery modern, platform digital untuk pemasaran karya, dan program magang internasional.',
                'development_status' => 'produktif',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Desa Nanggung — Tambang
            [
                'village_id' => 32010101,
                'created_by' => 1,
                'category' => 'tambang',
                'name' => 'Potensi Batu Andesit & Pasir',
                'description' => 'Deposit batu andesit dan pasir berkualitas di sepanjang aliran sungai Cidurian. Sumber material bangunan untuk wilayah Bogor dan sekitarnya.',
                'image' => 'https://picsum.photos/seed/potensi9/1200/800',
                'total_area' => 25.00,
                'production_volume' => 50000,
                'economic_value' => 7500000000,
                'is_investment_ready' => false,
                'investment_needs' => 'Kajian AMDAL, alat berat, dan reklamasi pasca tambang.',
                'development_status' => 'teridentifikasi',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Desa Ciampea — Peternakan
            [
                'village_id' => 32010301,
                'created_by' => 1,
                'category' => 'peternakan',
                'name' => 'Budidaya Lebah Madu Trigona',
                'description' => 'Budidaya lebah madu trigona (klanceng) yang menghasilkan madu berkhasiat tinggi. 150 koloni aktif dengan produksi 500 liter/tahun.',
                'image' => 'https://picsum.photos/seed/potensi10/1200/800',
                'total_area' => 3.00,
                'production_volume' => 500,
                'economic_value' => 1500000000,
                'is_investment_ready' => true,
                'investment_needs' => 'Stup modern, laboratorium pengujian kualitas madu, dan kemasan ekspor.',
                'development_status' => 'dikembangkan',
                'is_active' => true,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('village_potentials')->insert($potentials);
    }
}
