<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class VillageServiceSeeder extends Seeder
{
    public function run(): void
    {
        $services = [
            // Desa Nanggung
            [
                'village_id' => 32010101,
                'name' => 'Pembuatan KTP Elektronik',
                'slug' => 'pembuatan-ktp-elektronik-nanggung',
                'description' => 'Layanan pembuatan KTP Elektronik (e-KTP) bagi warga Desa Nanggung yang berusia 17 tahun ke atas atau sudah menikah.',
                'icon' => 'credit_card',
                'category' => 'administrasi_kependudukan',
                'requirements' => json_encode(['Fotokopi Kartu Keluarga', 'Surat Pengantar RT/RW', 'Akta Kelahiran', 'Pas Foto 3x4 (2 lembar)']),
                'process_steps' => 'Ambil formulir di kantor desa → Isi data dan lampirkan dokumen → Verifikasi oleh petugas → Perekaman biometrik → Tunggu pencetakan',
                'estimated_days' => 14,
                'fee' => 0,
                'contact_person' => 'Ibu Sri Wahyuni',
                'contact_phone' => '081234560101',
                'office_hours' => 'Senin-Jumat, 08:00-15:00',
                'is_online_available' => false,
                'online_url' => null,
                'is_active' => true,
                'usage_count' => 245,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'village_id' => 32010101,
                'name' => 'Surat Keterangan Usaha',
                'slug' => 'surat-keterangan-usaha-nanggung',
                'description' => 'Surat keterangan usaha untuk UMKM dan pelaku usaha kecil di Desa Nanggung. Diperlukan untuk perizinan dan akses permodalan.',
                'icon' => 'store',
                'category' => 'ekonomi',
                'requirements' => json_encode(['Fotokopi KTP', 'Fotokopi KK', 'Pas Foto 3x4', 'Surat Pengantar RT/RW', 'Foto Tempat Usaha']),
                'process_steps' => 'Ajukan ke kantor desa → Verifikasi lokasi usaha → Tanda tangan Kepala Desa → Ambil surat',
                'estimated_days' => 3,
                'fee' => 0,
                'contact_person' => 'Pak Andi',
                'contact_phone' => '081234560102',
                'office_hours' => 'Senin-Jumat, 08:00-15:00',
                'is_online_available' => true,
                'online_url' => 'https://nanggung.desa.id/layanan/sku',
                'is_active' => true,
                'usage_count' => 180,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Desa Malasari
            [
                'village_id' => 32010102,
                'name' => 'Surat Keterangan Tidak Mampu',
                'slug' => 'sktm-malasari',
                'description' => 'Surat keterangan bagi warga kurang mampu untuk mendapatkan bantuan kesehatan, pendidikan, atau bantuan sosial lainnya.',
                'icon' => 'volunteer_activism',
                'category' => 'sosial',
                'requirements' => json_encode(['Fotokopi KTP', 'Fotokopi KK', 'Surat Pengantar RT/RW', 'Bukti kondisi ekonomi']),
                'process_steps' => 'Datang ke kantor desa → Bawa dokumen persyaratan → Verifikasi data → Penerbitan surat',
                'estimated_days' => 2,
                'fee' => 0,
                'contact_person' => 'Bu Tini',
                'contact_phone' => '081234560201',
                'office_hours' => 'Senin-Jumat, 08:00-14:00',
                'is_online_available' => false,
                'online_url' => null,
                'is_active' => true,
                'usage_count' => 320,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'village_id' => 32010102,
                'name' => 'Posyandu Balita & Lansia',
                'slug' => 'posyandu-malasari',
                'description' => 'Pos pelayanan terpadu untuk pemantauan kesehatan balita dan lansia. Termasuk imunisasi, penimbangan, dan konsultasi gizi.',
                'icon' => 'health_and_safety',
                'category' => 'kesehatan',
                'requirements' => json_encode(['Buku KIA (untuk balita)', 'KTP Lansia', 'Kartu Posyandu']),
                'process_steps' => 'Datang sesuai jadwal → Registrasi → Penimbangan/Pemeriksaan → Konsultasi → Pemberian suplemen',
                'estimated_days' => 1,
                'fee' => 0,
                'contact_person' => 'Bidan Siti',
                'contact_phone' => '081234560202',
                'office_hours' => 'Setiap Rabu, 08:00-12:00',
                'is_online_available' => false,
                'online_url' => null,
                'is_active' => true,
                'usage_count' => 450,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Desa Ciampea
            [
                'village_id' => 32010301,
                'name' => 'Pembuatan Kartu Keluarga',
                'slug' => 'pembuatan-kk-ciampea',
                'description' => 'Layanan pembuatan atau pembaharuan Kartu Keluarga bagi warga Desa Ciampea.',
                'icon' => 'family_restroom',
                'category' => 'administrasi_kependudukan',
                'requirements' => json_encode(['Fotokopi KTP semua anggota keluarga', 'Akta Nikah/Cerai', 'Akta Kelahiran anak', 'Surat Pengantar RT/RW', 'KK Lama (jika pembaharuan)']),
                'process_steps' => 'Isi formulir → Lampirkan dokumen → Verifikasi petugas → Proses di Disdukcapil → Ambil KK baru',
                'estimated_days' => 14,
                'fee' => 0,
                'contact_person' => 'Pak Joko',
                'contact_phone' => '081234560301',
                'office_hours' => 'Senin-Kamis, 08:00-15:00, Jumat 08:00-11:00',
                'is_online_available' => true,
                'online_url' => 'https://ciampea.desa.id/layanan/kk',
                'is_active' => true,
                'usage_count' => 156,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'village_id' => 32010301,
                'name' => 'Pelatihan Kerajinan Bambu',
                'slug' => 'pelatihan-kerajinan-bambu-ciampea',
                'description' => 'Program pelatihan kerajinan bambu untuk warga desa. Belajar membuat furniture, dekorasi, dan peralatan rumah tangga dari bambu.',
                'icon' => 'school',
                'category' => 'pendidikan',
                'requirements' => json_encode(['KTP Warga Desa Ciampea', 'Usia 17-50 tahun', 'Formulir Pendaftaran']),
                'process_steps' => 'Daftar online/offline → Seleksi peserta → Ikuti pelatihan 2 minggu → Sertifikat → Pendampingan usaha',
                'estimated_days' => 14,
                'fee' => 50000,
                'contact_person' => 'Pak Bambang',
                'contact_phone' => '081234560302',
                'office_hours' => 'Senin-Sabtu, 09:00-16:00',
                'is_online_available' => false,
                'online_url' => null,
                'is_active' => true,
                'usage_count' => 89,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Desa Alamendah (Ciwidey)
            [
                'village_id' => 32040101,
                'name' => 'Izin Mendirikan Bangunan Desa',
                'slug' => 'imb-desa-alamendah',
                'description' => 'Layanan rekomendasi izin mendirikan bangunan di wilayah Desa Alamendah. Surat rekomendasi dari desa diperlukan sebelum mengajukan IMB ke kabupaten.',
                'icon' => 'construction',
                'category' => 'infrastruktur',
                'requirements' => json_encode(['Fotokopi KTP', 'Fotokopi Sertifikat Tanah/AJB', 'Denah Bangunan', 'Surat Pengantar RT/RW', 'Persetujuan Tetangga']),
                'process_steps' => 'Ajukan di kantor desa → Survei lokasi → Tanda tangan tetangga → Rekomendasi Kepala Desa → Lanjut ke Kecamatan',
                'estimated_days' => 7,
                'fee' => 25000,
                'contact_person' => 'Pak Deden',
                'contact_phone' => '081234560401',
                'office_hours' => 'Senin-Jumat, 08:00-14:00',
                'is_online_available' => false,
                'online_url' => null,
                'is_active' => true,
                'usage_count' => 67,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            // Desa Kuta Bali
            [
                'village_id' => 51080101,
                'name' => 'Surat Keterangan Domisili',
                'slug' => 'surat-domisili-kuta',
                'description' => 'Surat keterangan domisili untuk warga pendatang dan keperluan administrasi lainnya di Desa Kuta.',
                'icon' => 'location_on',
                'category' => 'pelayanan_umum',
                'requirements' => json_encode(['Fotokopi KTP', 'Fotokopi KK', 'Surat Pengantar RT/Banjar', 'Perjanjian Sewa/Kontrak (jika pendatang)']),
                'process_steps' => 'Datang ke kantor desa → Bawa dokumen lengkap → Verifikasi → Penerbitan surat (1 hari)',
                'estimated_days' => 1,
                'fee' => 0,
                'contact_person' => 'Ni Luh Ayu',
                'contact_phone' => '081234560501',
                'office_hours' => 'Senin-Sabtu, 08:00-14:00',
                'is_online_available' => true,
                'online_url' => 'https://kuta.desa.id/layanan/domisili',
                'is_active' => true,
                'usage_count' => 520,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        DB::table('village_services')->insert($services);
    }
}
